- name: Upgrade installed packages
  package: name=* state=latest

- name: Install packages requires to gather Pulp facts
  package: name={{ item }} state=present
  with_items:
      - git
      - rpm-build

- name: Gathering Pulp facts
  pulp_facts:
      devel_dir: "{{ pulp_devel_dir }}"

- name: Begin Building .bashrc
  copy:
    src: files/base.bashrc
    dest: "{{ unprivileged_homedir }}/{{ pulp_bashrc_filename }}"
    force: "{{ refresh_bashrc | default(false) }}"
  when: pulp_include_bashrc

- name: Touch .bashrc
  file:
    path: "{{ unprivileged_homedir }}/.bashrc"
    state: touch
    owner: "{{ ansible_user }}"

- name: Start a supplemental bashrc
  lineinfile:
    line: source {{ unprivileged_homedir }}/{{ pulp_bashrc_filename }}
    path: "{{ unprivileged_homedir }}/.bashrc"
    owner: "{{ ansible_user }}"
    insertafter: EOF
  when: pulp_include_bashrc
