- name: Install Optional useful packages
  package: name={{ item }} state=latest
  with_items:
      # System packages useful for most developers
      - bash-completion
      - fedora-easy-karma
      - htop
      - screen
      - tmux
      - tree
      - vim-enhanced
      - dstat
      - fpaste
      - iotop
      - jnettop
      - httpie
      - python-django-bash-completion
      - redhat-lsb-core
      - telnet
      - yum-utils
      # Python packages useful for developers
      - python-ipdb
      - python3-setuptools
      - python-rpdb

- name: Add developer aliases to .bashrc
  lineinfile:
    line: "{{ lookup('file', 'files/alias.bashrc') }}"
    path: "{{ unprivileged_homedir }}/{{ pulp_bashrc_filename }}"
  when: pulp_include_bashrc

- name: Add virtualenv environtment vars to .bashrc
  lineinfile:
    line: "{{ lookup('file', 'files/venv.bashrc') }}"
    path: "{{ unprivileged_homedir }}/{{ pulp_bashrc_filename }}"
  when: pulp_include_bashrc and (pulp_venv is defined)

- name: Add a basic .vimrc if it is not present
  lineinfile:
    line: "{{ lookup('file', 'files/vimrc') }}"
    path: "{{ unprivileged_homedir }}/.vimrc }}"
    force: no

 # - name: Link virtualenv project dirs
 #   lineinfile:
 #       dest: "{{ pulp_venv//.project"
 #       line: "{{ pulp_devel_dir }}/{{ item }}"
 #       create: true
 #       regexp: ".*"
 #   with_items: "{{ pulp_available_repositories | difference(pulp_available_plugins) }}"

