# - block:
#   - name: Create pulp-smash config dir
#     file:
#         path: "{{ unprivileged_homedir }}/.config/pulp_smash"
#         state: directory

#   - name: Install pulp-smash config
#     template:
#         src: templates/smash-settings.j2
#         dest: "{{ unprivileged_homedir }}/.config/pulp_smash/settings.json"

#   become: false
#   when: "{{ ['pulp-smash'] | issubset(pulp_available_repositories) }}"


